import { curriculumContentRegistry, CURRICULUM_STUDIES } from './curriculumContent.js';
const base = curriculumContentRegistry['OG.1.1.18'];
const standards = CURRICULUM_STUDIES.find(s=>s.id==='OG').standards.filter(s=>s.domain===1);
const verse=(reference,text,note)=>({reference,text,note});
const shema=verse('Deuteronomy 6:4','Hear, O Israel: The LORD our God is one LORD.','KJV. Hear the confession before reasoning about its implications.');
const mark=verse('Mark 12:29','The first of all the commandments is, Hear, O Israel; The Lord our God is one Lord:','KJV. Jesus repeats Israel’s confession when answering about the first commandment.');
const isaiah=[
 verse('Isaiah 43:10','before me there was no God formed, neither shall there be after me.','KJV excerpt. The claim excludes a deity before or after the LORD.'),
 verse('Isaiah 44:6','I am the first, and I am the last; and beside me there is no God.','KJV excerpt. Eternity and exclusivity belong together.'),
 verse('Isaiah 44:8','Is there a God beside me? yea, there is no God; I know not any.','KJV excerpt. The question is answered by God himself.'),
 verse('Isaiah 45:5','I am the LORD, and there is none else, there is no God beside me:','KJV excerpt. This is more than a claim to first place.'),
 verse('Isaiah 45:22','Look unto me, and be ye saved, all the ends of the earth: for I am God, and there is none else.','KJV. The exclusive God calls all the earth to salvation.'),
 verse('Isaiah 46:9','for I am God, and there is none else; I am God, and there is none like me,','KJV excerpt. Remembering God’s works supports the confession.')];
const nt=[
 verse('1 Corinthians 8:4-6','there is none other God but one.','KJV excerpt from verse 4. Open the passage: Paul contrasts so-called gods with one God, the Father, and one Lord Jesus Christ.'),
 verse('Ephesians 4:5-6','One Lord, one faith, one baptism, One God and Father of all, who is above all, and through all, and in you all.','KJV. Paul places the confession in the unity of the church.'),
 verse('1 Timothy 2:5','For there is one God, and one mediator between God and men, the man Christ Jesus;','KJV. Notice both one God and the mediator’s real humanity.'),
 verse('James 2:19','Thou believest that there is one God; thou doest well: the devils also believe, and tremble.','KJV. A correct confession must also be lived; recognition alone is insufficient.')];
const incarnation=[verse('John 1:1','In the beginning was the Word, and the Word was with God, and the Word was God.','KJV. Read through verse 14: the Word became flesh.'),verse('Matthew 28:19','baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:','KJV excerpt. Compare the command with Acts 2:38 in its full setting.'),verse('Acts 2:38','Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins,','KJV excerpt. Peter’s apostolic instruction names Jesus Christ.'),verse('Luke 22:42','Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done.','KJV. Jesus’ prayer is real; his humanity must not be erased.')];
const show=(id,title,teaching,scripture,next,visual,extra={})=>({id,type:'teach',stageId:'truth',phase:'Show me',title,teaching,scripture,next:{continue:next},visual,...extra});
const match=(id,title,prompt,items,options,next,standardId,extra={})=>({id,type:'scenario',stageId:'checkpoint',phase:'Guide me',title,prompt,teaching:['Make the connections yourself. After you check, we will look at the reasoning behind each connection. You can revise the ones that need another look.'],interaction:{type:'match',items,options},next:{strong:next,partial:id,weak:id},standardIds:[standardId],evidenceIds:[],...extra});
const attempt=(id,title,prompt,standard,next,scripture)=>({id,type:'free_response',stageId:'checkpoint',phase:'Let me try',title,prompt,teaching:['Use your own explanation. The support drawer is available if you need it; opening it makes this a supported attempt. A fresh attempt without support is needed to establish independent understanding.'],standardIds:[standard.id],assessmentCriteria:standard.evidence.map(e=>e.text),evidenceIds:standard.evidence.map(e=>`${standard.id}:evidence-${e.level}`),scripture,next:{strong:next,partial:id,weak:id}});
const moves=[
 show('learn','One confession. One unfolding story.',[
  'Imagine hearing “God is one” in four different settings: Israel gathered to listen, Isaiah challenging rival claims, Jesus answering a question, and the apostles teaching the church. Does the confession change as the story unfolds?',
  'We will investigate that question together. You will learn to explain the Shema, weigh Isaiah’s declarations, trace the New Testament connections, state the difference between Oneness and trinitarian teaching accurately, and connect the confession to worship and conduct.',
  'Five standards belong to this connected lesson. Your place is saved between its chapters; you do not need to finish the whole lesson in one sitting.'
 ],[shema],'shema-show','story',{cta:'Follow the confession'}),
 show('shema-show','Listen before you define',[
  'Hear is a summons to Israel. “The LORD our God” identifies the one Israel belongs to. “One LORD” is the confession that governs how the rest of the revelation is understood. Deuteronomy 6:5 immediately calls Israel to wholehearted love.',
  'Shema is the Hebrew word for “hear”; echad means “one.” A word can occur in different settings. Genesis 2:24 describes two people as one flesh, but that does not decide what Deuteronomy says about God. Read the word with the subject and the surrounding declarations.',
  'In this Apostolic lesson, Isaiah’s exclusion of any other God and Jesus’ repetition of the Shema establish the context for numerical oneness. We will reason from those passages rather than asking a single dictionary word to carry the whole argument.'
 ],[shema,mark],'shema-guide','scroll'),
 match('shema-guide','Rebuild the confession','Match each phrase with the job it does.',[
  {id:'hear',label:'Hear, O Israel',answer:'summons',explanation:'The opening addresses a people and calls them to listen.'},
  {id:'our',label:'The LORD our God',answer:'identity',explanation:'This identifies Israel’s God and the covenant relationship.'},
  {id:'one',label:'is one LORD',answer:'confession',explanation:'The confession concerns who God is, not just agreement within a group.'}
 ],[{id:'confession',label:'Confesses God’s oneness'},{id:'summons',label:'Calls Israel to listen'},{id:'identity',label:'Identifies the covenant God'}],'shema-try',standards[0].id),
 attempt('shema-try','Explain the anchor', 'State Deuteronomy 6:4 from memory and explain its phrases in ordinary language. Why does it remain the framework when Jesus and the apostles speak? A friend points to “one flesh” in Genesis 2:24: explain why context, including Isaiah, must decide the meaning rather than that comparison alone. Connect Mark 12:29, 1 Corinthians 8:4–6, and Ephesians 4:5–6.',standards[0],'isaiah-show',[shema,mark,...isaiah.slice(0,2),...nt.slice(0,2)]),
 show('isaiah-show','The witness stand',[
  'Isaiah 43 calls for witnesses. The issue is not which rival deity deserves first place. The LORD declares that no God was formed before him and none will follow. The later declarations add “beside me” and “none else.” Together they exclude rivals across time and alongside God.',
  'Watch the three directions in the visual: before, beside, after. These are a way to organize the words, not a picture of God. Isaiah 45 also connects the one God to salvation for all the earth.',
  'Read all six witnesses below. When another passage introduces language you find difficult, hold it beside this established confession instead of silently replacing the confession.'
 ],isaiah,'isaiah-guide','exclusivity'),
 match('isaiah-guide','Test the rival claims','Choose the declaration that most directly answers each claim.',[
  {id:'earlier',label:'“Perhaps an earlier deity made this God.”',answer:'before',explanation:'Isaiah 43:10 explicitly excludes a God formed before the LORD.'},
  {id:'alongside',label:'“Another God could exist alongside him.”',answer:'beside',explanation:'Isaiah 44:6 directly rules out a God beside him.'},
  {id:'local',label:'“This God can only call Israel to salvation.”',answer:'earth',explanation:'Isaiah 45:22 calls all the ends of the earth to the one God.'}
 ],[{id:'earth',label:'Isaiah 45:22 · all the ends of the earth'},{id:'before',label:'Isaiah 43:10 · no God before me'},{id:'beside',label:'Isaiah 44:6 · no God beside me'}],'isaiah-try',standards[1].id,{activityLabel:'Evidence challenge'}),
 attempt('isaiah-try','Make the cumulative case','Quote four of Isaiah’s declarations from memory and explain what each contributes. Connect their combined claim to New Testament monotheism. Someone argues, “Isaiah excludes other gods but says nothing against eternal divine persons within one God.” Explain the Apostolic response to that actual argument, using the wording and context rather than calling the other person a polytheist.',standards[1],'continuity-show',isaiah),
 show('continuity-show','Follow the same thread',[
  'Jesus answers with the Shema. Paul then says there is no other God but one before addressing “one God, the Father” and “one Lord Jesus Christ.” Read the surrounding contrast with so-called gods: the confession is not introduced as permission to add deities.',
  'Ephesians places one God in the church’s shared confession. First Timothy joins one God to a real human mediator. James affirms one God while warning that recognition without a faithful response is insufficient.',
  'The Apostolic reading keeps Jesus’ identity and real humanity within this monotheistic framework. “Father” and “Lord” must be explained in the passages, not merely counted as labels and turned into a number of gods.'
 ],[mark,...nt],'continuity-guide','story'),
 match('continuity-guide','Build the Scripture trail','Place each witness at its place in this argument: confession → reaffirmation → apostolic application.',[
 {id:'paul',label:'Paul: “there is none other God but one”',answer:'application',explanation:'Paul applies monotheism while addressing idols and the church’s life.'},
 {id:'moses',label:'Israel: “The LORD our God is one LORD”',answer:'foundation',explanation:'Deuteronomy supplies the foundational confession.'},
 {id:'jesus',label:'Jesus: “The first … Hear, O Israel”',answer:'affirmation',explanation:'Mark records Jesus reaffirming the confession.'}
 ],[{id:'foundation',label:'1 · Foundational confession'},{id:'affirmation',label:'2 · Jesus’ reaffirmation'},{id:'application',label:'3 · Apostolic application'}],'continuity-try',standards[2].id,{activityLabel:'Build the argument'}),
 attempt('continuity-try','Answer a new reading','A reader says, “The Old Testament has one God, but Paul adds a second divine person in 1 Corinthians 8:6.” Build a short response from Deuteronomy through Jesus to Paul and James. Explain the contribution of 1 Corinthians 8:4–6, Ephesians 4:5–6, 1 Timothy 2:5, and James 2:19, including why the Apostolic reading sees continuity rather than a revised confession.',standards[2],'distinction-show',[shema,mark,...nt]),
 show('distinction-show','Represent the claim fairly',[
  'Trinitarian theology confesses one divine essence in three coequal, coeternal persons. It does not describe itself as belief in three gods. Essence concerns what God is; person concerns the distinctions it affirms. “Proceeding” describes the Spirit’s relation of origin in that theology; it does not mean the Spirit was created later.',
  'Oneness teaching rejects eternal distinctions of divine persons. The one God is revealed as Father, in the Son through genuine incarnation, and as the Holy Spirit. Jesus is truly God and truly human. His humanity is not a costume, so his prayer and obedience must be taken seriously.',
  'Compare John 1:1 with 1:14, and Matthew 28:19 with Acts 2:38. The Apostolic reading sees the Word becoming flesh and the name of Jesus expressed in apostolic baptism. A trinitarian reader interprets these through eternal personal distinctions. The disagreement must be explained at that point, not disguised by repeating “one God,” which both claim.'
 ],incarnation,'distinction-guide','comparison',{sourceCredit:'Reinforcement: UPCI, Our Beliefs; The True Humanity of Jesus Christ. Summary of the one God’s revelation and genuine incarnation; Scripture remains the basis of the lesson.'}),
 match('distinction-guide','Repair the explanation','Classify each claim before trying to answer it.',[
 {id:'three',label:'“Trinitarians teach three separate gods.”',answer:'misstates',explanation:'This misstates their claim of one divine essence. Critique the actual distinction of persons.'},
 {id:'persons',label:'“One divine essence, three coeternal persons.”',answer:'trinitarian',explanation:'This states the trinitarian position accurately enough to identify the disagreement.'},
 {id:'human',label:'“The one God became truly human in Jesus; his prayers are real.”',answer:'oneness',explanation:'Genuine incarnation is essential to the Oneness explanation of Jesus’ prayers.'},
 {id:'acting',label:'“Jesus only pretended to pray.”',answer:'misstates',explanation:'Oneness does not erase Jesus’ real humanity or turn his prayer into playacting.'}
 ],[{id:'oneness',label:'Accurate Oneness claim'},{id:'misstates',label:'Misrepresents a position'},{id:'trinitarian',label:'Accurate trinitarian claim'}],'distinction-try',standards[3].id,{activityLabel:'Claim clinic'}),
 attempt('distinction-try','Teach it to someone who disagrees','Explain both positions fairly, including essence, person, and proceeding. Show where their readings of John 1:1 and Matthew 28:19 alongside Acts 2:38 differ. Then answer, “If Jesus is God, who was he praying to?” Ground the Apostolic explanation in genuine incarnation and Scripture. Bring back the Shema and Isaiah as the framework, without dismissing the other person.',standards[3],'devotion-show',[shema,...incarnation,...nt.slice(2,3)]),
 show('devotion-show','One Lord. An undivided response.',[
  'The next verse after the Shema commands love for God with all the heart, soul, and might. Confession leads directly to allegiance. The first commandment excludes rival gods; the second forbids making an image to worship. God does not receive a compartment of life while another authority governs the rest.',
  'Doxology means praise directed to God. Ethics concerns how we live. Mission concerns carrying the gospel to others. The confession reaches all three: worship belongs to the one Lord, conduct answers to his authority, and the gospel calls people everywhere to him.',
  'A learner might win an argument about oneness and still treat a neighbor dishonestly. James warns that recognition alone is insufficient. Our final chapter asks what a faithful response looks like without requiring you to disclose private experiences.'
 ],[verse('Deuteronomy 6:5','And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.','KJV. The command immediately follows the confession.'),verse('Exodus 20:3-5','Thou shalt have no other gods before me.','KJV excerpt from verse 3. Read verses 4–5 for the prohibition of images and bowing down to them.'),nt[3]],'devotion-guide','devotion'),
 {id:'devotion-guide',type:'scenario',stageId:'checkpoint',phase:'Guide me',title:'Choose the next faithful step',standardIds:[standards[4].id],teaching:['A fictional church group teaches one God clearly. It then proposes hiding a financial mistake to protect its reputation. One member says, “Our doctrine is right; this is just business.” Consider the consequence of each response.'],prompt:'Which response carries the confession into the situation?',authoredFeedback:true,
 choices:[
 {id:'separate',label:'Keep teaching the doctrine; business decisions use a separate moral standard.',teachingMessage:'This divides allegiance. If the one Lord governs all life, public teaching cannot excuse dishonest conduct. Return to the demand for the whole heart.'},
 {id:'honest',label:'Keep the confession, correct the record, and treat affected people honestly.',teachingMessage:'This connects confession with conduct. Correction does not earn salvation; it expresses a response to the one Lord’s authority. The same allegiance shapes worship and the way the gospel is shared.'},
 {id:'abandon',label:'Stop discussing doctrine because only behavior matters.',teachingMessage:'Deuteronomy joins knowing this God with loving him. Replacing confession with behavior breaks that connection too. Bring belief and conduct together.'}
 ],expectedChoiceIds:['honest'],evidenceIds:[],next:{strong:'devotion-try',partial:'devotion-guide',weak:'devotion-guide'}},
 attempt('devotion-try','Bring the confession into life','Someone says, “Oneness is only an argument about numbers.” Explain Deuteronomy 6:4–5 together and relate them to the first two commandments. Give a concrete example in each area: worship, honest conduct, and sharing the gospel with others. Explain how exclusive devotion to the one Lord connects the examples and strengthens community. Use fictional situations if you prefer.',standards[4],'complete',[shema,verse('Deuteronomy 6:5','And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.','KJV.'),nt[3]]),
 {id:'complete',type:'complete',stageId:'mastery',title:'One story, five connections.'}
];
for(const [index,prefix] of ['shema','isaiah','continuity','distinction','devotion'].entries()) {
 moves.find(m=>m.id===`${prefix}-show`).standardIds=[standards[index].id];
}
// Work through all connected concepts before asking for their independent synthesis.
const guidedRoute={'shema-guide':'isaiah-show','isaiah-guide':'continuity-show','continuity-guide':'distinction-show','distinction-guide':'devotion-show','devotion-guide':'shema-try','shema-try':'isaiah-try','isaiah-try':'continuity-try','continuity-try':'distinction-try','distinction-try':'devotion-try'};
for(const [id,next] of Object.entries(guidedRoute))moves.find(m=>m.id===id).next.strong=next;
const orderedMoves=[];
let cursor='learn';
while(cursor){const move=moves.find(m=>m.id===cursor);orderedMoves.push(move);cursor=move.next?.continue || move.next?.strong;}
const knowledge=standards.flatMap(s=>s.evidence.map(e=>({id:`${s.id}:evidence-${e.level}`,title:`${s.title}: ${e.label}`,description:e.text})));
export default {...base,standardId:'OG.1.LESSON.18',standardTitle:'One God: the confession through Scripture',lessonFormat:'teacher-led',coveredStandards:standards,instructionalMoves:orderedMoves,curriculumVersion:1,
 sourceDomain:{...base.sourceDomain,vocabulary:[{term:'Shema',definition:'Hebrew for hear; the opening word used to name Israel’s confession in Deuteronomy 6:4.'},{term:'Echad',definition:'Hebrew for one. Interpret the word in the setting of the passage; this lesson develops its Apostolic interpretation alongside Isaiah’s declarations.'},{term:'Monotheism',definition:'Belief in one God.'},{term:'Incarnation',definition:'God becoming truly human in Jesus Christ; his humanity is genuine.'},{term:'Essence and person',definition:'In trinitarian theology, essence identifies the one divine being and person identifies the three eternal distinctions. Oneness rejects those eternal personal distinctions.'},{term:'Doxology',definition:'Praise directed to God; this lesson connects confession to worship.'}]},
 completionSummary:'You investigated the confession, weighed Isaiah’s witnesses, traced New Testament continuity, explained the doctrinal distinction fairly, and connected the confession to life.',
 takeaways:['Read the Shema within its covenant and scriptural context.','Let Isaiah’s declarations accumulate into an argument.','Trace the confession through Jesus and the apostles.','Represent another position accurately before explaining the Apostolic response.','Connect the confession to worship, ethics, and mission.'],
 presets:Object.fromEntries(Object.entries(base.presets).map(([id,p])=>[id,{...p,currentMoveId:'learn',currentStageId:'truth'}])),
 brain:{...base.brain,masteryTarget:standards.map(s=>s.statement).join('\n'),requiredKnowledge:knowledge,evidenceOfUnderstanding:knowledge,requiredScripture:[shema,mark,...isaiah,...nt,...incarnation],teacherGuardrails:[...base.brain.teacherGuardrails,'Assess only the current standard. All its listed criteria must be demonstrated for strong. Do not infer recall from copied support. Be precise and respectful about trinitarian beliefs. Teach the supplied Apostolic interpretation without presenting a caricature of other Christians.']}};
