/**
 * vocabularyGlossary.js — AI-DRAFTED, PENDING REVIEW
 *
 * The master documents ("The One True God" / "The New Birth" Standards
 * Master Documents) list vocabulary terms per standard but never define
 * them — that content simply doesn't exist yet. Every definition below was
 * drafted by Claude, grounded in the statement/instructionalFocus text of
 * the standard(s) that cite each term (never from outside theological
 * knowledge), specifically so a learner has something to read before being
 * tested. These are NOT yet Brain-authoritative. Review, correct, or
 * replace any entry before treating it as settled doctrine — the Brain
 * principle ("standards are the brain") applies to this file exactly like
 * every other doctrinal source: nothing here should be trusted only
 * because Jeremiah AI generated it.
 *
 * Keyed by the exact term string as it appears in a standard's
 * `vocabulary` array. Look up via getVocabularyDefinition(term), which
 * matches case-insensitively so small casing differences in the source
 * data still resolve.
 */

export const vocabularyGlossary = {
  "Access to God": "The nearness to God that the new birth grants — the covenant-fulfillment counterpart to the barriers sin created, made possible through Christ's atoning work.",
  "Acts Pattern": "The recurring sequence of repentance, baptism in Jesus' name, and reception of the Spirit that the book of Acts records as the apostles' consistent response to the gospel.",
  "Adonai": "A Hebrew title meaning \"Lord\" or \"Master,\" used throughout the Old Testament for God and applied to Jesus in the New Testament as evidence of His identity as YHWH incarnate.",
  "Apologetics": "The reasoned defense of a doctrinal position — in this curriculum, the practice of accurately naming and answering alternative views of God's identity (trinitarianism, Arianism, Unitarianism, modalism, and others) from Scripture.",
  "Apostolic Consistency": "The doctrinal significance of the Book of Acts recording the same repentance-baptism-Spirit pattern repeatedly, rather than a one-time or improvised event.",
  "Apostolic Fathers": "The earliest generation of Christian writers after the apostles (late 1st–early 2nd century), whose practice of baptizing in Jesus' name and worshiping Him as the one God incarnate is cited as evidence that oneness, not trinitarian, belief was the church's original position.",
  "Apostolic Fellowship": "The shared covenant life and community — not merely private belief — that the new birth brings a believer into.",
  "Apostolic Opening": "Pentecost's role as the historical starting point of new-covenant salvation, opened in fulfillment of prophecy rather than as an isolated spiritual event.",
  "Apostolic Pattern": "The commanded, repeated shape of gospel response the apostles taught and modeled — repentance, baptism in Jesus' name, and reception of the Spirit.",
  "Apostolic revelation": "The Spirit-given clarity at Pentecost through which the identity, exaltation, and lordship of Jesus Christ were publicly proclaimed.",
  "Apostolic Standard": "The full, scripturally complete apostolic teaching on the new birth, against which partial or reduced salvation claims are measured and found insufficient.",
  "Apostolic witness": "The public, structured proclamation of who Jesus Christ is and what He accomplished, as modeled in Peter's sermon in Acts 2:22–36.",
  "Arianism": "The 4th-century position (associated with Arius) that the Son is a created being, distinct from and subordinate to God the Father in essence — one of the alternative views this curriculum requires students to accurately define and answer.",
  "Aseity": "The attribute of God's self-existence — that He depends on nothing outside Himself for His being, and is the uncaused source of all else that exists.",
  "Atoning Death": "Christ's death understood as the payment that satisfies the penalty of sin, forming (with His burial and resurrection) the redemptive foundation the new birth stands on.",
  "Authority of the Name": "The covenantal weight carried by the name of Jesus in salvation — not a peripheral detail but the authority under which repentance, baptism, and forgiveness are enacted.",
  "Baptismal Obedience": "Water baptism understood as a commanded act of obedience to the gospel, not an optional symbol — inseparable from apostolic new-birth teaching.",
  "Blood": "The blood of Christ's sacrifice, the preparatory biblical category (alongside covenant and cleansing) through which the logic of the new birth is established.",
  "Bodily (somatikos)": "The Greek term behind Colossians 2:9 (\"the fullness of the Godhead bodily\") — meaning Christ's deity dwells in Him in actual physical, embodied form, not symbolically or partially.",
  "Body of Christ": "The church understood as one organism formed by one gospel, one Spirit, and one covenant life, not a loose association of individual believers.",
  "Bridge doctrine": "The way Pentecost connects and fulfills what was promised in the Old Testament to what the apostles then proclaimed about Jesus' identity and lordship.",
  "Burial": "Christ's burial, the middle term of death-burial-resurrection that forms the redemptive foundation of the new birth and the pattern water baptism enacts.",
  "Burial with Christ": "The theological meaning Paul gives water baptism (Romans 6) — identification with Christ's burial, giving baptism significance beyond a symbolic washing.",
  "Canon": "The recognized, authoritative body of Scripture — the completed revelation that Hebrews 1:1–2 describes God speaking through, culminating in His Son.",
  "Change of Direction": "The active, behavioral dimension of repentance — an actual turning away from sin toward God, not simply a change of feeling.",
  "Church": "The community formed by one gospel, one Spirit, and one covenant life — the body the new birth incorporates a believer into.",
  "Church Birth": "Pentecost understood as the founding moment of the church as a new-covenant community, not merely an individual spiritual experience.",
  "Church Identity": "What defines the church doctrinally — one gospel, one Spirit, one covenant life — as distinct from any looser or merely social definition.",
  "Classical Trinitarianism": "The historic doctrine that God eternally exists as three distinct persons — Father, Son, and Holy Spirit — sharing one divine essence; named here as a position students must accurately represent before answering it.",
  "Cleansed Conscience": "The inward result of remission of sins — not merely a legal pardon but a genuinely cleared conscience before God.",
  "Cleansing": "The removal of sin's defilement, one of the preparatory biblical categories (with sacrifice and blood) that the new birth fulfills.",
  "Comforter (Paraclete)": "A title for the Holy Spirit (from the Greek parakletos, \"one called alongside to help\") describing the Spirit's role as helper and advocate to believers.",
  "Communicable attributes": "Qualities of God's character — such as love, holiness, and mercy — that human beings can reflect or share in, unlike the incommunicable attributes that belong to God alone.",
  "Confession": "The verbal acknowledgment of sin and turning to God that accompanies genuine repentance in apostolic salvation teaching.",
  "Consistent Response": "The doctrinal weight of Acts recording the same gospel response — repentance, baptism, Spirit reception — again and again, rather than as an unrepeated exception.",
  "Continuity of the Spirit": "The single identity of the Holy Spirit at work across all of Scripture — from creation and the prophets, through Christ's ministry, into the life of the church — rather than a Spirit who changes or is introduced only at Pentecost.",
  "Conversion Narrative": "The Acts accounts of individuals and groups coming to faith, treated as doctrinally significant patterns rather than merely historical anecdotes.",
  "Conviction": "The inward awareness of sin and need for God that the Spirit produces, leading a person toward repentance.",
  "Corruption": "The moral ruin sin introduces into human nature — part of what Scripture means by the Fall's effect on humanity, and part of why the new birth is necessary.",
  "Council of Nicea (325 AD)": "The church council that produced the Nicene Creed's formulation of Christ's relationship to the Father — a key milestone this curriculum treats as part of the historical development of trinitarian doctrine, centuries after the apostles.",
  "Covenant": "God's binding relational commitment to His people, the framework within which both creation and the new birth are understood as fulfillments rather than isolated events.",
  "Covenant Application": "How remission, cleansing, and washing function within apostolic salvation teaching — not abstract ideas but doctrinal descriptions of what the new birth actually accomplishes for a believer.",
  "Covenant Community": "The corporate, relational dimension the new birth creates — belonging to God's people, not merely a private transaction with God.",
  "Covenant Entry": "Water baptism's role as the point at which a believer formally enters the new covenant, inseparable from the gospel response the apostles taught.",
  "Covenant Entry Name": "The name of Jesus as the covenantal authority under which a believer enters the new birth through baptism.",
  "Covenant Fulfillment": "The new birth understood as the fulfillment of God's earlier promises and covenants, not a spiritual experience detached from biblical history.",
  "Covenant Opening": "Pentecost as the point at which the new covenant's promised blessings — the Spirit poured out — began to be given.",
  "Covenant Response": "Repentance as the required human response that opens the way into covenant relationship with God.",
  "Creation ex nihilo": "The doctrine that God created the universe out of nothing, by His own power alone, rather than shaping pre-existing matter.",
  "Dead Faith": "Belief that stops at mental agreement without obedient response — the kind of faith this curriculum's new-birth teaching says is insufficient for salvation.",
  "Death": "Physical and spiritual death, the consequence the Fall introduced into human life, alongside corruption, alienation, and judgment.",
  "Defense": "The fourth and highest evidence-of-learning level in this curriculum — the ability to hold a doctrinal position under real challenge from an opposing view, using Scripture.",
  "Discernment": "The ability to accurately identify and distinguish between competing doctrinal positions, a prerequisite this curriculum requires before students argue against any of them.",
  "Divine Indwelling": "God's presence dwelling within the believer, part of the covenant reality the new birth establishes.",
  "Divine operation": "The Holy Spirit's activity understood as the work of the one true God Himself, not a separate divine being or an impersonal force.",
  "Doctrinal Community": "The church as a body defined and held together by shared doctrine, not merely shared sentiment or association.",
  "Doctrinal Distortion": "A teaching that alters or waters down the full apostolic doctrine of the new birth — something students are trained to name specifically, not just sense vaguely.",
  "Doctrinal Endurance": "The capacity to hold a doctrinal position with clarity and composure over time and under pressure, rather than folding when challenged.",
  "Doctrinal Omission": "Leaving out an essential element of apostolic salvation teaching (such as baptism or Spirit reception) while presenting what remains as the whole gospel.",
  "Doctrinal Practice": "The lived, repeated pattern of belief and action (such as the Acts pattern of repentance, baptism, and Spirit reception) that carries doctrinal weight because of its consistency.",
  "Dual nature": "The teaching that Jesus Christ is fully God and fully human at once — one person with both a divine and a human nature — which this curriculum distinguishes from any teaching that this implies two separate persons.",
  "Dual nature principle": "The interpretive rule that Christ's statements and actions in the Gospels must each be understood as flowing from either His human nature or His divine nature, resolving apparent tensions (like Mark 13:32) without dividing Him into two persons.",
  "Earnest Contention": "Contending sincerely and firmly for the truth of the new birth doctrine, paired in this curriculum with gentleness rather than harshness.",
  "Echad": "The Hebrew word for \"one\" in the Shema (Deuteronomy 6:4); in this curriculum's usage it grounds the claim that God's oneness is numerical and absolute, not a \"compound unity\" that would allow for multiple divine persons.",
  "Economic Trinity": "The idea that Father, Son, and Holy Spirit are three distinct persons acting in different roles in salvation history — referenced here as the view this curriculum contrasts with its reading of Matthew 28:19's singular \"name.\"",
  "El / Elohim": "Hebrew names/titles for God (\"El\" a general term for deity, \"Elohim\" its plural-form usage for the one true God), part of the array of divine names this curriculum shows applied to Jesus in the New Testament.",
  "El Shaddai": "A Hebrew name for God traditionally rendered \"God Almighty,\" one of the Old Testament divine names this curriculum connects to Jesus as evidence of His full deity.",
  "Entry into the Church": "Becoming part of the body of Christ, a communal result of the new birth rather than something separate from it.",
  "Entry Response": "The repentance-baptism-Spirit sequence understood as the doctrinally significant \"entry\" pattern by which a person comes into apostolic salvation.",
  "Eschatological subjection (1 Cor. 15:28)": "Paul's statement that the Son will ultimately be \"subject\" to the Father — read in this curriculum through the dual-nature principle as describing Christ's human nature and mediatorial role, not a permanent inferiority within the Godhead.",
  "Eternal generation": "The classical trinitarian doctrine that the Son is eternally \"begotten\" of the Father; this curriculum instead teaches that \"Son of God\" language originates at the incarnation, not in an eternal relationship before it.",
  "Exaltation": "Jesus' being raised to the position of Lord and Christ, publicly declared at Pentecost as the fulfillment of what His identity always was.",
  "Exaltation (Acts 2:36)": "Peter's climactic declaration that God has made Jesus \"both Lord and Christ\" — the public vindication of His identity and lordship following the resurrection.",
  "Express image (charakter)": "The Greek term (Hebrews 1:3) describing Christ as the exact representation of God's being — used here alongside Colossians 2:9 to establish His full and complete deity.",
  "Faith": "Obedient trust in God's revealed gospel — in this curriculum's usage, more than mental agreement, but a trust that acts on what it believes.",
  "False Assurance": "Confidence of salvation built on a partial or selective reading of the gospel rather than the full apostolic new-birth pattern.",
  "Father (as divine designation)": "One of three distinct biblical uses of \"Father\" for God this curriculum identifies: (1) Creator/sovereign Father of all, (2) covenant Father of Israel, and (3) the divine Spirit dwelling within the incarnate Son.",
  "Finished Work": "Christ's death, burial, and resurrection considered as a completed redemptive accomplishment, not an ongoing or partial process.",
  "Forgiveness": "The removal of guilt granted through remission of sins — a specific doctrinal provision tied to the gospel response, not generic religious comfort.",
  "Fruit of the Spirit": "The Spirit-produced character qualities (Galatians 5:22–23) that mark transformed living as the expected continuation of the new birth, not self-generated moral effort.",
  "Fulfillment Event": "Pentecost understood as the historical moment at which earlier prophetic promises about the Spirit were actually fulfilled.",
  "Full deity": "The teaching that Jesus Christ possesses the complete nature and attributes of God, not a partial, derivative, or lesser divinity.",
  "General revelation": "What can be known about God through creation and providence, in contrast to special revelation given directly through Scripture and Christ.",
  "Gethsemane prayer": "Jesus' prayer in the garden (\"not my will, but thine, be done\") cited as an example of statements to be understood through His human nature under the dual-nature principle, not as evidence of two divine wills.",
  "Gift of the Spirit": "The Holy Spirit given to believers as the fulfilled promise of new-covenant indwelling life, essential rather than optional to the new birth.",
  "Godly Sorrow": "Grief over sin that is directed toward God and produces genuine repentance (2 Corinthians 7:10), distinguished from regret that merely feels bad about consequences.",
  "Gospel": "The good news of Christ's redemptive death, burial, and resurrection — an accomplished act requiring a revealed response, not mere information to agree with.",
  "Gospel Obedience": "Acting on the gospel through faith that includes obedient response, rather than treating belief and obedience as separate or competing categories.",
  "Gospel Response": "The full pattern of repentance, baptism, and Spirit reception the apostles taught as the appropriate reply to the gospel's redemptive accomplishment.",
  "Grace": "God's unearned favor toward sinners, which in this curriculum's framing is received through — not competing with — obedient response to the gospel.",
  "Greek Apologists": "Second-century Christian writers who used Greek philosophical vocabulary (such as Logos) to explain Christian belief to a Hellenistic audience — described in this curriculum as part of the conceptual bridge to later trinitarian formulation.",
  "Guilt": "The state of moral liability before God that sin produces, part of what the new birth addresses.",
  "Holiness": "The moral attribute of God's absolute purity and separateness from sin, and by extension the standard of life God calls His people to.",
  "Holy of Holies": "The innermost chamber of the tabernacle/temple, where God's presence dwelt above the ark — a type this curriculum connects to the incarnation, the church, and the individual believer as places God chooses to dwell.",
  "Holy Spirit": "The Spirit of the one true God — not a separate divine being or an impersonal force, but God Himself active in creation, prophecy, Christ's ministry, and the life of the church.",
  "Holy Spirit (as divine designation)": "One of the three titles named in Matthew 28:19's singular \"name,\" identified in this curriculum with the one God's active presence rather than a distinct third person.",
  "Human Condition": "Humanity's fallen state of guilt, corruption, and separation from God introduced by the Fall — the doctrinal backdrop that makes the new birth necessary.",
  "Identity-bearing practice": "An action (such as invoking the name of Jesus) that carries and communicates who a person belongs to and what they believe, not merely a ritual gesture.",
  "Immutability": "God's unchanging nature — that His character, purposes, and being do not shift or develop over time.",
  "Inaugurated eschatology": "The idea that the promised future has already begun breaking into the present — for instance, that Christ's coming inaugurated the \"last days\" spoken of by the prophets, even though final fulfillment is still to come.",
  "Incarnation": "God the Son — in this curriculum's usage, God Himself — taking on human nature and being born as Jesus Christ, beginning at His miraculous conception.",
  "Incommunicable attributes": "Qualities that belong to God alone and cannot be shared with or reflected by creatures — aseity, omniscience, omnipotence, omnipresence, and immutability — all of which this curriculum teaches were fully present in Jesus Christ.",
  "Indwelling": "God's presence dwelling within a person or place — traced in this curriculum from the tabernacle, through the incarnation, to the church and the individual believer.",
  "Invocation": "Calling on the name of Jesus, an act tied in apostolic teaching to repentance, baptism, and the remission of sins.",
  "Jesus / Yeshua": "The Hebrew name Yeshua (\"the LORD saves\") behind the Greek name Jesus — in this curriculum's framing, the name of the one true God incarnate, applied in the New Testament with the same authority as the Old Testament's divine names.",
  "Judgment": "God's righteous verdict against sin, part of the consequence the Fall introduced and part of why salvation is necessary rather than optional.",
  "Kenosis": "From the Greek word for \"emptying\" (Philippians 2:7) — the incarnation understood as the Son taking on human limitation, not the loss of His deity.",
  "Kenotic passages": "Scripture passages (such as Mark 13:32) that appear to show Christ's knowledge or power as limited — read in this curriculum through the dual-nature principle as describing His human nature, not a limit on His deity.",
  "Kerygma": "The Greek word for \"proclamation\" — the core apostolic preaching content about who Jesus is and what He accomplished, as modeled in Acts 2:22–36.",
  "Kingdom Life": "Life lived under God's rule as the ongoing expression of the new birth — transformed, Spirit-produced conduct rather than a one-time event with no continuation.",
  "Kyrios": "The Greek word for \"Lord,\" used in the Septuagint to translate God's name YHWH and applied directly to Jesus in the New Testament as evidence of His full deity.",
  "Living Faith": "Faith that includes obedient response to the gospel, as distinguished in this curriculum from faith that is mere mental agreement.",
  "Lordship declaration": "The public proclamation (as in Acts 2:36) that Jesus is Lord — an assertion about His identity and authority, not just a title of respect.",
  "Manifest in the flesh": "The phrase from 1 Timothy 3:16 — in this curriculum's reading, meaning God Himself, not a divine representative or second person, took on human flesh in Jesus Christ.",
  "Manifestation": "A visible or recognizable expression of the Spirit's presence and activity, treated in apostolic teaching as a real, expected part of receiving the Spirit rather than a purely internal or theoretical event.",
  "Matthew 28:19 — singular \"name\"": "The observation that Jesus commands baptism \"in the name\" (singular, not \"names\") of the Father, Son, and Holy Spirit — read in this curriculum as showing that one name, not three, encompasses all three titles.",
  "Meekness": "A gentle, humble strength — the posture this curriculum pairs with doctrinal firmness when defending the new birth under challenge.",
  "Mental Assent": "Intellectual agreement with a truth claim, without accompanying trust or obedience — insufficient, in this curriculum's teaching, as saving faith.",
  "Modalism": "The teaching that God is one person who appears in three different modes or roles (Father, Son, Spirit) at different times — named here as a historic label sometimes (this curriculum argues, inaccurately) applied to Oneness apostolic theology, which it distinguishes from true modalism.",
  "Monotheism": "The belief that there is only one God — the foundational claim of the Shema (Deuteronomy 6:4) and the interpretive framework this curriculum applies to all later revelation about God.",
  "Monotheistic exclusivity": "The scriptural insistence, especially in Isaiah, that God alone is God and no other being shares His identity — language this curriculum reads as excluding any plurality of divine persons.",
  "Monotheistic interpretation": "Reading Holy Spirit language in Scripture through the lens of biblical monotheism — as the one God's own Spirit, not a second or third divine being.",
  "Name Confession": "Publicly acknowledging and calling on the name of Jesus as central to a believer's response to the gospel.",
  "Name Invocation": "Calling on the name of Jesus specifically within water baptism, tying the act to the authority and covenant significance apostolic teaching gives that name.",
  "Name of Jesus": "In apostolic proclamation, the revealed disclosure of who God is in Christ — carrying identity, authority, and covenant significance, not functioning as a mere label.",
  "Name-Bearing Response": "Responding to the gospel by calling on and identifying with the name of Jesus, as apostolic teaching connects that name to repentance, baptism, and remission.",
  "Necessary Gift": "The Holy Spirit understood as essential — not optional supplemental empowerment — for entering the kingdom of God.",
  "Need for Salvation": "The doctrinal conclusion that follows from sin's guilt, corruption, and separation — that salvation is necessary, not optional, for every person.",
  "New Birth": "The apostolic doctrine of salvation as a genuine spiritual rebirth (John 3:5) — encompassing repentance, water baptism in Jesus' name, and receiving the Holy Spirit — rather than a single isolated moment or belief alone.",
  "New-Covenant Birth": "The new birth understood specifically as the opening act of the new covenant, publicly begun at Pentecost in fulfillment of prophecy.",
  "New-Covenant Identification": "The recognizable, Spirit-given marks (including the sign of tongues in Acts) that identify a person as having entered new-covenant life.",
  "New-Covenant Life": "Ongoing life under the new covenant, made possible by the indwelling Holy Spirit given as God's promised gift.",
  "Newness of Life": "The transformed manner of living (Romans 6:4) that flows from and continues the new birth, produced by the Spirit rather than self-generated.",
  "Normative Practice": "A pattern (such as the Acts sequence of repentance, baptism, and Spirit reception) treated as the standard expectation for all believers, not an exception limited to the apostolic era.",
  "Numerical oneness": "The claim that God's oneness in the Shema is a strict, singular oneness — one being, not one essence shared among multiple persons.",
  "Obedience": "Compliance with God's commands as the fitting, expected response of a believer who has received the new birth, not a separate or optional add-on to salvation.",
  "Obedience of Faith": "Faith that inherently includes obedient action, reflecting this curriculum's teaching that saving faith and obedience are not in competition with grace but part of how grace is received.",
  "Observable Manifestation": "A visible, recognizable sign (such as tongues) accompanying the Spirit's reception, treated in apostolic teaching as a genuine expected occurrence.",
  "Omnipresence": "God's attribute of being present everywhere at once, not limited to any single place.",
  "One Baptism": "Water baptism understood as a single, unified apostolic ordinance — commanded, connected to remission, and inseparable from new-birth doctrine.",
  "One Body": "The church as a single unified body formed by one gospel, one Spirit, and one covenant life.",
  "Oneness Pentecostalism": "The apostolic theological tradition affirmed throughout this curriculum: that God is one indivisible being (not three eternal persons) who is fully revealed and incarnate in Jesus Christ, and that salvation follows the Acts pattern of repentance, baptism in Jesus' name, and receiving the Holy Spirit.",
  "Origen": "An early-3rd-century Alexandrian theologian whose use of Greek philosophical categories (such as \"eternal generation\") is cited in this curriculum as an influence on later trinitarian formulation, centuries after the apostles.",
  "Partial Salvation Claim": "A claim to salvation that leaves out one or more essential elements of apostolic new-birth doctrine while presenting itself as sufficient.",
  "Pentecost": "The day (Acts 2) the Holy Spirit was poured out on the church, publicly proclaiming Jesus' identity, exaltation, and lordship in fulfillment of prophecy.",
  "Personal language": "Scripture's use of personal pronouns and relational descriptions for the Holy Spirit — read in this curriculum as describing the one God's own active presence, not an impersonal force or separate being.",
  "Philosophical theism": "A general, abstract belief in a supreme being arrived at through reason rather than revelation — contrasted in this curriculum with the specific, revealed, exclusive monotheism of the Shema.",
  "Progressive revelation": "The biblical pattern of God disclosing truth about Himself gradually over time, culminating in the final and complete revelation given through Jesus Christ (Hebrews 1:1–2).",
  "Promise": "God's covenant commitment to His people, part of the preparatory biblical structure that the new birth later fulfills.",
  "Promise of the Spirit": "The Old Testament and Christ's own promise that God would give His Spirit to His people, fulfilled in the gift of the Holy Spirit at and after Pentecost.",
  "Prophetic fulfillment": "The pattern of Old Testament prophecy being realized in the person and work of Christ, treated as doctrinally significant rather than coincidental.",
  "Protoevangelion": "The \"first gospel\" — the earliest promise of redemption in Scripture (Genesis 3:15), pointing forward to Christ's victory over sin and death.",
  "Providence": "God's ongoing sovereign care and governance over creation, distinct from but related to His initial act of creating.",
  "Public Sign": "A visible, communal marker (such as the events of Pentecost) that publicly and unmistakably signals a doctrinal reality rather than a private or hidden one.",
  "Purification": "The removal of sin's defilement through the gospel's cleansing provision, part of what remission of sins accomplishes.",
  "Readiness": "Being doctrinally and spiritually prepared to defend the new birth's truth under challenge with clarity and composure.",
  "Recognition": "The first and most basic evidence-of-learning level in this curriculum — recalling and identifying a doctrinal truth, prior to explaining, applying, or defending it.",
  "Reconciliation": "The restoration of relationship between God and humanity accomplished through Christ, whose full deity (Colossians 2:9) is what makes that reconciling work sufficient.",
  "Redemptive Application": "How remission and cleansing are applied to a believer's actual standing before God, not left as abstract theological ideas.",
  "Redemptive Basis": "Christ's death, burial, and resurrection as the foundational accomplishment on which the entire doctrine of the new birth rests.",
  "Redemptive Structure": "The larger biblical framework of promise, covenant, sacrifice, and cleansing that the new birth fulfills rather than replaces.",
  "Reductionism": "Presenting a selective or partial version of new-birth doctrine as though it were the complete apostolic teaching.",
  "Regeneration": "Being spiritually reborn — a necessary, essential requirement for entering the kingdom of God, not optional empowerment added on top of salvation.",
  "Remission": "The forgiveness and removal of sins, a doctrinal provision apostolic teaching ties directly to baptism in Jesus' name (Acts 2:38).",
  "Renewal": "The Spirit's work of making a believer new, part of what the promised gift of the Holy Spirit accomplishes in new-covenant life.",
  "Renunciation": "The deliberate rejection of sin and self-rule involved in genuine repentance, not merely feeling sorry for wrongdoing.",
  "Repentance": "Turning from sin to God — a commanded, necessary response to the gospel that includes surrendering self-rule to God's authority, not optional moral advice.",
  "Restitution": "Making right what was wronged as a practical outworking of genuine repentance.",
  "Resurrection": "Christ's rising bodily from the dead, the climactic third element (with His death and burial) of the redemptive foundation the new birth stands on.",
  "Revealed Authority": "The covenantal authority carried by the name of Jesus, under which the new birth is entered — not human or institutional authority.",
  "Revealed Pattern": "The consistent repentance-baptism-Spirit sequence in Acts, understood as a doctrinally significant pattern God revealed through the apostles rather than incidental narrative detail.",
  "Right-hand language": "Scripture's description of Christ being seated \"at the right hand\" of God (Acts 2:33) — exaltation language expressing supreme authority, not a claim about physical location or a second divine throne.",
  "Sacrifice": "The Old Testament sacrificial system, a preparatory biblical category (with blood and cleansing) that establishes the logic the new birth later fulfills.",
  "Salvation Minimalism": "Reducing salvation to the smallest possible requirement, at the expense of the full apostolic new-birth pattern.",
  "Salvation Pattern": "The doctrinally significant, repeated shape of gospel response recorded throughout Acts.",
  "Sanctified Life": "A life set apart for God as the fitting expression of new-covenant salvation and belonging, flowing from — not earning — the new birth.",
  "Saving Faith": "Obedient trust in the gospel that includes response, not mental agreement alone — this curriculum's apostolic definition of the faith that actually saves.",
  "Saving Name": "The name of Jesus as the specific, necessary name under which salvation and covenant entry occur, not one option among many.",
  "Scriptural Fullness": "The complete apostolic teaching on the new birth, which this curriculum holds must be preserved intact rather than selectively read down.",
  "Selective Reading": "Interpreting Scripture's teaching on faith, grace, or experience narrowly, in a way that distorts the fuller doctrine of the new birth.",
  "Sensus plenior": "A Latin term meaning \"fuller sense\" — the idea that an Old Testament passage can carry a deeper, Christ-centered meaning than its original human author fully grasped, later revealed in the New Testament.",
  "Separated Living": "A life visibly set apart from sin, presented in this curriculum as a fitting response to new-covenant salvation rather than legalistic performance.",
  "Separation": "Alienation from God caused by sin, part of the human condition that makes the new birth necessary.",
  "Shekinah": "A traditional Hebrew term (not itself in the biblical text) for the visible glory-presence of God, such as that which filled the tabernacle and temple.",
  "Sign Dimension": "The observable, sign-bearing aspect of receiving the Spirit — specifically speaking in tongues — that apostolic texts treat as doctrinally significant, not incidental.",
  "Sin": "Rebellion against God — the cause of human guilt, corruption, and separation, and the reason the new birth is necessary rather than optional.",
  "Son (as divine designation)": "One of the three titles in Matthew 28:19's singular \"name\" — in this curriculum's usage, referring to God's incarnate identity in Jesus Christ, not a distinct eternal second person.",
  "Son of God (incarnational meaning)": "The title \"Son of God\" understood as originating at the incarnation — the miraculous conception by the Holy Spirit — rather than describing an eternal relationship between separate divine persons before Christ's birth.",
  "Special revelation": "Truth about God disclosed directly through Scripture and through Christ Himself, in contrast to general revelation available through creation.",
  "Spirit Birth": "Being born of the Spirit (John 3:5) — the essential spiritual dimension of the new birth, necessary for entering the kingdom of God.",
  "Spirit Evidence": "A recognizable sign, particularly speaking in tongues, that apostolic texts connect to genuinely receiving the Holy Spirit.",
  "Spirit Outpouring": "The public giving of the Holy Spirit at Pentecost, fulfilling prophetic promise and opening new-covenant birth.",
  "Spirit Reception": "Receiving the Holy Spirit as a real, recognizable event within apostolic salvation doctrine, not merely a theoretical or invisible transaction.",
  "Spiritual Birth": "Being born again by the Spirit, an essential and necessary requirement of salvation rather than optional spiritual enrichment.",
  "Spiritual Formation": "The ongoing shaping of a believer's character by the Spirit, continuing and expressing the new birth in daily life.",
  "Spiritual Union": "The believer's shared life with Christ and with other believers, formed by one gospel, one Spirit, and one covenant life.",
  "Stable Foundation": "A settled, well-grounded doctrinal footing that allows a believer to withstand challenges to the new birth without being shaken.",
  "Subordination texts": "Passages that appear to describe the Son as subordinate to the Father — read in this curriculum through the dual-nature principle as describing Christ's human nature or mediatorial role, not a lesser divine status.",
  "Substitutionary Suffering": "Christ's suffering understood as taking the place of sinners, satisfying what their sin deserved — part of the redemptive basis of the new birth.",
  "Surrender": "Yielding self-rule to God's authority, a dimension of repentance this curriculum treats as essential, not optional.",
  "Tabernacle": "The portable Old Testament sanctuary where God's presence dwelt among Israel — a type this curriculum connects to the incarnation, the church, and the individual believer as later fulfillments of God's desire to dwell with His people.",
  "Tertullian": "A late-2nd/early-3rd-century North African church father credited with early use of the Latin terms (\"trinitas,\" \"persona\") later foundational to trinitarian formulation — cited here as part of that doctrine's post-apostolic historical development.",
  "Testimony": "A believer's clear, composed account and defense of the new birth's truth, especially under challenge.",
  "The Fall": "Adam and Eve's original sin (Genesis 3), which introduced corruption, alienation, shame, judgment, and death into human life and created the need for salvation.",
  "The Shema": "Deuteronomy 6:4 (\"Hear, O Israel: The LORD our God is one LORD\") — Israel's foundational confession of monotheism and, in this curriculum, the interpretive anchor for everything Scripture later says about God's identity.",
  "Theophany": "A visible appearance or manifestation of God, such as those recorded throughout the Old Testament and connected in this curriculum to the tabernacle and the incarnation.",
  "Theotes": "The Greek word behind Colossians 2:9 (\"the fullness of the Godhead\") — referring to God's essential nature or deity itself, not merely divine qualities or attributes.",
  "Transformed Living": "Changed conduct and character that flows from the new birth as its expected fruit, produced by the Spirit rather than self-generated effort.",
  "Trust": "Reliance on God's revealed gospel that goes beyond intellectual agreement — the obedient dimension apostolic teaching requires of saving faith.",
  "Turning": "The core action of repentance — deliberately turning away from sin and toward God.",
  "Type / Antitype": "A biblical pattern in which an earlier person, event, or object (the type — such as the tabernacle) foreshadows a later, fuller fulfillment (the antitype — such as the incarnation or the church).",
  "Typology": "The study of how Old Testament persons, events, and institutions foreshadow New Testament fulfillment, particularly in Christ.",
  "Unashamed Witness": "Testifying to the truth of the new birth openly and without embarrassment, even under pressure or challenge.",
  "Unitarianism": "The position that God is a single person (denying any distinction reflected in Father, Son, and Spirit language as applying to Christ's deity) and that Jesus is not fully God — named here as one of the alternative views students must accurately define and distinguish from Oneness apostolic theology.",
  "Victory over Death": "Christ's resurrection understood as His decisive triumph over death, part of the redemptive foundation the new birth rests on.",
  "Vindication": "The resurrection's role as public proof and confirmation of who Jesus Christ actually is, not merely evidence that He returned to life.",
  "Visible Community": "The church as a publicly identifiable body of believers, not merely an invisible or private spiritual reality.",
  "Washing": "A biblical image for cleansing from sin, one of the covenant-application categories (with remission) describing what the new birth accomplishes.",
  "Water Baptism": "Baptism in water in the name of Jesus, commanded as part of apostolic gospel response and doctrinally connected to both remission of sins and identification with Christ's burial.",
  "Word (Logos)": "The title for Christ in John 1:1 (\"in the beginning was the Word\") describing His eternal existence, distinguished in this curriculum from the incarnational \"Son\" language of John 1:14 as two dimensions of the one person Jesus Christ, not two persons.",
  "World-Facing Stability": "The composed, grounded confidence a believer maintains when the new birth's doctrine is challenged by outsiders.",
  "Worship Life": "A believer's devotion and worship as a fitting response to salvation, flowing from God's nature and the believer's covenant identity.",
  "YHWH (Yahweh)": "The personal, covenant name of God revealed in the Old Testament (translated \"LORD\" in most English Bibles) — applied directly to Jesus in New Testament texts like Philippians 2:9–11 and Romans 10:13 as evidence of His identity as the one true God.",
  "Yielded Belief": "Faith that includes yielding to God's authority in obedient response, not belief held at arm's length from one's actions.",
};

/** Case-insensitive lookup, since source data casing isn't perfectly consistent. */
export function getVocabularyDefinition(term) {
  if (!term) return "";
  if (vocabularyGlossary[term]) return vocabularyGlossary[term];
  const key = Object.keys(vocabularyGlossary).find(
    (k) => k.toLowerCase() === term.toLowerCase()
  );
  return key ? vocabularyGlossary[key] : "";
}
